### ISSUE TITLE
config.js in gitignore, preventing local build

### ISSUE THREAD

**Issue by Lenni009** [MeridianGH/kalliope-server#2]
The config.js file is included in `.gitignore`. Since `main.js` imports data from there, the local build fails if the config is not present.

If there are any API keys or other sensitive data in there, please consider adding them as environment variables to your deployment instead.

**Comment by MeridianGH** [comment]
I never thought about the fact that someone might build this project locally, therefore I quickly threw together an improvised solution for secrets.

Keep in mind that you will need to provide the required information of a [Discord Application](https://discord.com/developers/applications) to be able to use the dashboard in your local build.

Fixed in 2559490
